### ISSUE TITLE
Where does one get the reverse engineered Krunker source?

### ISSUE THREAD

**Issue by Draphar** [hrt/WheelChair#131]

**Comment by hrt** [comment]
@Draphar Getting it yourself using this extension is not so simple.

First you would have to modify the extension to load your local `wheelchair.js` instead of this repositories remote `wheelchair.min.js`.

Then you would have to modify `wheelchair.js` using a solution like [this](https://stackoverflow.com/a/18197341) to download the string variable [`script`](https://github.com/hrt/WheelChair/blob/master/wheelchair.js#L385). You could alternatively log the variable to the console and try to copy paste it from there however there's limits placed on how much content your clipboard can hold.
