### ISSUE TITLE
he is updating the user script probably as we speak so no worries

### ISSUE THREAD

**Issue by ItsCasuals** [hrt/WheelChair#47]
just try to calm down and keep playing

**Comment by michaelshumshum** [comment]
its time to start playing legitmately

**Comment by DiptooD** [comment]
Updated yet ?

**Comment by michaelshumshum** [comment]
> Updated yet ?

he said 14 hours

**Comment by PatheticMustan** [comment]
If you're being redirected, it means there's a new version since the hacks have last been patched.
This is to protect you from any potential updates to anti-cheat, I think.
If you want to remove this restriction, you run the risk of _**getting your account banned**_.

To remove the restriction, remove lines 331-336.

**Removing this may get your account banned.**

**Comment by hrt** [comment]
Update done. Remove the old script
