### ISSUE TITLE
I CANT PLAY KRUNKER

### ISSUE THREAD

**Issue by jacobyson** [hrt/WheelChair#58]
HELLO, EVERYTIME I GO ON KRUNKER.IO IT DIRECTS ME TO HERE, why

**Comment by RayTheGod12** [comment]
It directs you to here because it is outdated right now. Inusha is still working on the code and the version of this code is 1.8.8 not 1.8.9.. So stop trying to try the code it will not work and only bring you here to the homepage of his github. Just turn off tamper or find a working code in version 1.8.9

**Comment by maplesyrup1111** [comment]
i have no clue how to do that and yah same thing happening to me:( please try to make it soon i am dying 👎  🚨

**Comment by hrt** [comment]
Update done. Remove the old script
